---
- name: Create backup directory if not exist
  file:
    path: /home/oracle/backup
    state: directory

- name: Create AAG backup installation home
  archive:
    path: /app/Axway-7.7.0
    dest: /home/oracle/backup/Axway-7.7.0_{{ ansible_date_time.date }}_full_backup.tar.gz
    format: gz
