---
- name: Check OAM Node Manager process
  shell: "pgrep -f 'startNodeManager'"
  register: nodemanager_process_check
  ignore_errors: yes
  changed_when: False
  failed_when: False

- name: Check OAM Managed server process
  shell: "pgrep -f '/IAMAccessDomain/config/fmwconfig/servers/wls_oam'"
  register: managed_process_check
  ignore_errors: yes
  changed_when: False
  failed_when: False

- name: Check OAM Managed server process
  shell: "pgrep -f '/IAMAccessDomain/config/fmwconfig/servers/wls_ama'"
  register: ama_process_check
  ignore_errors: yes
  changed_when: False
  failed_when: False

- name: Check OAM Admin Server process
  shell: "pgrep -f '/mnt/nfs/config/aserver/domains/IAMAccessDomain/bin/startWebLogic.sh'"
  register: admin_process_check
  ignore_errors: yes
  when: 
    - inventory_hostname == 'oam1.{{ ap }}.{{ env }}.ccn2.taxud'
  changed_when: False
  failed_when: False



- name: Shutdown OAM Managed Server - OAM node1
  shell: 
    cmd: "./stopManagedWebLogic.sh {{ managed_servers_node1[0].managed_server_node1 }} {{ admin_server_url }}:{{ admin_server_port}}"
    chdir: "{{ managed_server_domain }}/bin"
  register: stopManagedServer_out
  when: 
    - inventory_hostname == 'oam1.{{ ap }}.{{ env }}.ccn2.taxud'
    - managed_process_check.rc == 0

- name: Shutdown OAM Managed Server - OAM node2
  shell: 
    cmd: "./stopManagedWebLogic.sh {{ managed_servers_node2[0].managed_server_node2 }} {{ admin_server_url }}:{{ admin_server_port}}"
    chdir: "{{ managed_server_domain }}/bin"
  register: stopManagedServer2_out
  when: 
    - inventory_hostname == 'oam2.{{ ap }}.{{ env }}.ccn2.taxud'
    - managed_process_check.rc == 0

##### ama
- name: Shutdown OAM AMA1 Server - AMA node1
  shell: 
    cmd: "./stopManagedWebLogic.sh {{ managed_servers_node1[1].managed_server_node1 }} {{ admin_server_url }}:{{ admin_server_port}}"
    chdir: "{{ managed_server_domain }}/bin"
  register: stopManagedServer_out
  when: 
    - inventory_hostname == 'oam1.{{ ap }}.{{ env }}.ccn2.taxud'
    - ama_process_check.rc == 0

- name: Shutdown OAM AMA2 Server - AMA node2
  shell: 
    cmd: "./stopManagedWebLogic.sh {{ managed_servers_node2[1].managed_server_node2 }} {{ admin_server_url }}:{{ admin_server_port}}"
    chdir: "{{ managed_server_domain }}/bin"
  register: stopManagedServer2_out
  when: 
    - inventory_hostname == 'oam2.{{ ap }}.{{ env }}.ccn2.taxud'
    - ama_process_check.rc == 0
####

- name: Shutdown OAM Admin Server 
  shell:
    cmd: "./stopWebLogic.sh"
    chdir: "{{ admin_server_domain }}/bin"
  register: stopAdminServer_out
  when: 
    - inventory_hostname == 'oam1.{{ ap }}.{{ env }}.ccn2.taxud'
    - admin_process_check.rc == 0

- name: Shutdown OAM NodeManager
  shell:
    cmd: "./stopNodeManager.sh"
    chdir: "{{ managed_server_domain }}/bin"
  register: stopNodeManager_out
  when: 
    - nodemanager_process_check.rc != 0