---
- name: Check OUD status
  command: "/app/ldap_instance/OUD/bin/status --no-prompt --script-friendly"
  register: ldap_instance_status
  changed_when: false

- name: Shutdown OUD Instance
  shell:
    cmd: "/app/ldap_instance/OUD/bin/stop-ds"
  when: "'Server Run Status: Started' in ldap_instance_status.stdout"
  register: stopoud_out

- debug:
    var: stopoud_out.stdout_lines
