---
- name: create backup directory if not exist
  file:
    path: /home/oracle/backup
    state: directory

- name: create backup of OHS configuration files - /app/config
  archive:
    path: /app/config
    dest: /home/oracle/backup/OHS_config_{{ ansible_date_time.date }}_full_buckup.tar.gz
    format: gz

- name: create backup of OHS fmwOHS12214
  archive:
    path: /app/fmwOHS12214
    dest: /home/oracle/backup/fmwOHS12214_{{ ansible_date_time.date }}_full_buckup.tar.gz
    format: gz