---
- name: Upload SPBAT OAM Bundle Patch {{ oam_bundle_archive }}
  copy:
    src: "{{ patches_dir_oam }}/{{ oam_bundle_archive }}"
    dest: "{{ binaries_dir }}/{{ oam_bundle_archive }}"

- name: Unzip Patch OAMbundle
  shell:
    cmd: "unzip -o {{ oam_bundle_archive }}"
    chdir: "{{ binaries_dir }}"

- name: Execute pre stop phase spbat script
  shell:
    cmd: "{{ binaries_dir }}/{{ oam_spbat_patch_id }}/tools/spbat/generic/SPBAT/spbat.sh -type oam -phase prestop -mw_home {{ oam_oracle_home }} -spb_download_dir {{ binaries_dir }}/{{ oam_spbat_patch_id }}"
  register: spbat_out
- debug:
    var: spbat_out.stdout_lines

- name: Execute downtime phase spbat script
  shell:
    cmd: "{{ binaries_dir }}/{{ oam_spbat_patch_id }}/tools/spbat/generic/SPBAT/spbat.sh -type oam -phase downtime -mw_home {{ oam_oracle_home }} -spb_download_dir {{ binaries_dir }}/{{ oam_spbat_patch_id }}"
  register: spbat_out
- debug:
    var: spbat_out.stdout_lines

- name: Execute post start phase spbat script
  shell:
    cmd: "{{ binaries_dir }}/{{ oam_spbat_patch_id }}/tools/spbat/generic/SPBAT/spbat.sh -type oam -phase poststart -mw_home {{ oam_oracle_home }} -spb_download_dir {{ binaries_dir }}/{{ oam_spbat_patch_id }}"
  register: spbat_out
- debug:
    var: spbat_out.stdout_lines
