---
- name: Upload Java {{ jdk_archive }}
  copy:
    src: /app/binaries/Java/{{ jdk_archive }}
    dest: "{{ binaries_dir }}/{{ jdk_archive }}"

- name: Unzip Java
  unarchive:
    src: "{{ binaries_dir }}/{{ jdk_archive }}"
    dest: "/app"
    remote_src: yes
#    extra_opts: [--strip-components=0]

- name: Move old jdk with other name
  shell: "mv /app/jdk /app/{{ old_jdk }}"

- name: Move new jdk with other name
  shell: "mv /app/{{ new_jdk }} /app/jdk"


- name: Check Java Version
  shell:
    cmd: /app/jdk/bin/java -version 2>&1| awk -F '"' ' /version/ {print "jdk" $2}'
  register: java_version
- debug:
    var: java_version.stdout_lines[0]

- name: Stop playbook when old version of Java
  fail:
    msg: "Old version Java detected. Playbook stopped"
  when: java_version.stdout_lines[0] != "{{ new_jdk }}"



# - name: Move old jdk with other name
#   file:
#     src: "/app/jdk/"
#     dest: "/app/{{ old_jdk }}"
#     state: directory
#     remote_src: yes
#     force: yes

# - name: Move new jdk with other name
#   file:
#     src: "/app/{{ new_jdk }}"
#     dest: "/app/jdk"
#     state: directory
#     remote_src: yes
#     force: yes