---
- name: Create backup directory if not exist
  file:
    path: /home/oracle/backup
    state: directory

- name: Create backup of OUD ldap instance
  archive:
    path: /app/ldap_instance
    dest: /home/oracle/backup/ldap_instance_{{ ansible_date_time.date }}_full_backup.tar.gz
    format: gz

- name: Create backup of OUD oracle home - {{ oracle_home_oud }}
  archive:
    path: "{{ oracle_home_oud }}"
    dest: /home/oracle/backup/fmwOUD12214_{{ ansible_date_time.date }}_full_backup.tar.gz
    format: gz
